[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "erdantic"
version = "0.6.0"
description = "Entity relationship diagrams for Python data model classes like Pydantic."
readme = "README.md"
authors = [{ name = "DrivenData", email = "info@drivendata.org" }]
license = { file = "LICENSE" }
keywords = ["erd", "entity relationship diagram", "dataclasses", "pydantic"]
classifiers = [
  "Intended Audience :: Developers",
  "Topic :: Software Development :: Code Generators",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
]
requires-python = ">=3.7"
dependencies = [
  "importlib_metadata ; python_version < '3.8'",
  "pydantic >= 2",
  "pydantic-core",
  "pygraphviz",
  "typer",
  "typing_extensions > 4 ; python_version < '3.8'",
]

[project.optional-dependencies]
tests = ["pytest>=6,<8", "pytest-cases"]

[project.scripts]
erdantic = "erdantic.cli:app"

[project.urls]
"Repository" = "https://github.com/drivendataorg/erdantic"
"Documentation" = "https://erdantic.drivendata.org/"
"Bug Tracker" = "https://github.com/drivendataorg/erdantic/issues"
"Changelog" = "https://erdantic.drivendata.org/stable/changelog/"

## DEFAULT ENVIRONMENT ##

[tool.hatch.envs.default]
type="conda"
command="mamba"
conda-forge=true
pre-install-commands = [
  "mamba install graphviz -y",
]
features = ["tests"]
dependencies = ["ipython", "mypy>=1.0.0", "ruff>=0.1.14"]
python = "3.10"

[tool.hatch.envs.default.scripts]
lint = ["ruff format --check {args:.}", "ruff check {args:.}"]
typecheck = ["mypy {args:repro_tarfile.py cli} --install-types --non-interactive"]

## DOCS ENVIRONMENT ##

[tool.hatch.envs.docs]
dependencies = [
  "mdx_truly_sane_lists==1.3",
  "mike",
  "mkdocs>=1.2.2",
  "mkdocs-jupyter",
  "mkdocs-material>=7.2.6",
  "mkdocstrings[python-legacy]>=0.19.0",
]

## TESTS ENVIRONMENT ##

[tool.hatch.envs.tests]
type="conda"
command="mamba"
conda-forge=true
pre-install-commands = [
  "mamba install graphviz -y",
]
features = ["tests"]
dependencies = ["coverage>=6.5", "pytest-cov"]
template = "tests"

[[tool.hatch.envs.tests.matrix]]
python = ["3.8", "3.9", "3.10", "3.11", "3.12"]

[tool.hatch.envs.tests.scripts]
test = "pytest {args:tests} -v --cov=. --cov-report=term --cov-report=html --cov-report=xml"

## TOOLS ##

[tool.ruff]
line-length = 99
src = ["erdantic/**/*.py", "tests/**/*.py"]

[tool.ruff.lint]
select = [
  "E", # Pyflakes
  "F", # Pycodestyle
  "I", # isort
]
unfixable = ["F"]

[tool.ruff.lint.isort]
known-first-party = ["erdantic"]
force-sort-within-sections = true

[tool.mypy]
ignore_missing_imports = true

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--cov=erdantic --cov-report=term --cov-report=html --cov-report=xml"
testpaths = ["tests"]

[tool.coverage.run]
source = ["erdantic"]
