site_name: erdantic
site_url: https://erdantic.drivendata.org/
site_description: Draw entity relationship diagrams for Pydantic models and standard library dataclasses.
repo_url: https://github.com/drivendataorg/erdantic
theme:
  name: material

nav:
  - Home: "index.md"
  - CLI Help: "cli.md"
  - Usage Examples:
      - Pydantic: "examples/pydantic.ipynb"
      - dataclasses: "examples/dataclasses.ipynb"
  - API Reference:
      - erdantic.erd: "api-reference/erd.md"
      - erdantic.pydantic: "api-reference/pydantic.md"
      - erdantic.dataclasses: "api-reference/dataclasses.md"
      - erdantic.examples:
          - erdantic.examples.pydantic: "api-reference/examples.pydantic.md"
          - erdantic.examples.dataclasses: "api-reference/examples.dataclasses.md"

plugins:
  - search
  - mkdocs-jupyter
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            filters: ["!^_(?!_init__)"]
            inherited_members: true
          rendering:
            show_root_heading: false
            show_root_toc_entry: false
            show_root_full_path: false
            show_if_no_docstring: true
            show_source: true
            heading_level: 2
      watch:
        - erdantic
